# Generated by Django 2.0.5 on 2018-09-07 06:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 9, 7, 6, 14, 1, 226835, tzinfo=utc), verbose_name='阅读日期')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='readnum',
            name='read_num',
            field=models.IntegerField(default=0, verbose_name='阅读总数'),
        ),
    ]
