# Generated by Django 2.0.5 on 2018-09-11 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_auto_20180907_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 11, 7, 35, 44, 605220, tzinfo=utc), verbose_name='阅读日期'),
        ),
    ]
