# Generated by Django 2.0.5 on 2018-09-13 07:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0005_auto_20180913_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readdetail',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 9, 13, 7, 10, 26, 535409, tzinfo=utc), verbose_name='阅读日期'),
        ),
    ]
